---
- name: Install docker package
  ansible.builtin.apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Install nginx package
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes